/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;

/**
 *
 * @author Michael Coitim 
 * 
 * +
 */
public class TelaMensagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaMensagem
     */
    public TelaMensagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMen = new javax.swing.JTextField();
        btnCri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMenCri = new javax.swing.JTextField();
        btnDes = new javax.swing.JButton();
        deslocamento = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMenDes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mensagem");

        txtMen.setForeground(new java.awt.Color(51, 51, 51));
        txtMen.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMen.setText("digite  sua mensagem ");
        txtMen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMenMouseClicked(evt);
            }
        });
        txtMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenActionPerformed(evt);
            }
        });

        btnCri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCri.setText("criptografar");
        btnCri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mensagem criptografada");

        txtMenCri.setForeground(new java.awt.Color(51, 51, 51));
        txtMenCri.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMenCri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenCriActionPerformed(evt);
            }
        });

        btnDes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDes.setText("descriptografar");
        btnDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesActionPerformed(evt);
            }
        });

        deslocamento.setModel(new javax.swing.SpinnerNumberModel(1, 1, 26, 1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Deslocamento");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Tradutor Cifra de César");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mensagem Descriptografada");

        txtMenDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenDesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(btnCri, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(btnDes, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(deslocamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMen, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMenDes, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMenCri, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deslocamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCri, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMenCri, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMenDes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMenCriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenCriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenCriActionPerformed

    private void txtMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtMenActionPerformed

    private void txtMenDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenDesActionPerformed

    private void btnCriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriActionPerformed
        
        String mensagem =txtMen.getText();
        String criptada ="";
        //sString retorno;
        int chave = Integer.parseInt(deslocamento.getValue().toString());
          char aux1, aux2;  
           for(int i=0; i < mensagem.length(); i++ ){
               
                // sub espaço por espacço
            if (mensagem.charAt(i)==32){
                criptada+=" ";

            }
             
                // tratamento das letra minusculas
            if(mensagem.charAt(i) >= 97 && mensagem.charAt(i)<= 122){
                if((int) (mensagem.charAt(i) + chave)>122){
                    aux1 = (char) (mensagem.charAt(i) + chave);
                    aux2 = (char) (aux1 - 122);
                    criptada= criptada+ (char)(96 + aux2);
                    // retorno= criptada;
                    txtMenCri.setText(criptada);
                  
                }else{
                    criptada= criptada + (char) (mensagem.charAt(i) + chave);
                    //retorno= criptada;
                    txtMenCri.setText(criptada);
                    
                }
            
            }
                //Tratamento Letras mausculas
                if (mensagem.charAt(i) >=65 && mensagem.charAt(i) <=90){
                    if (mensagem.charAt(i) + chave > 90){
                        aux1= (char) (mensagem.charAt(i) + chave);
                        aux2 = (char) (aux1 -90);
                         criptada= criptada+ (char)(aux2+64);
                         txtMenCri.setText(criptada);
                    }else{
                        criptada = criptada + (char)(mensagem.charAt(i)+ chave);
                        txtMenCri.setText(criptada);
                    }
                    
                }  // tratamento dos numeros 
              if(mensagem.charAt(i) >=48 && mensagem.charAt(i) <=57){
                    if(mensagem.charAt(i) + chave > 57){
                       aux1 = (char) (mensagem.charAt(i) + chave);
                       aux2 = (char) (aux1 -57) ;
                       criptada= criptada + (char) ( 47+aux2);
                        txtMenCri.setText(criptada);
                        
                    } else{
                        criptada+= (char) (mensagem.charAt(i) + chave);
                        txtMenCri.setText(criptada);
                    }
              }
            
            
                      
        } 
    }//GEN-LAST:event_btnCriActionPerformed

    private void txtMenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenMouseClicked
        txtMen.setText(" ");
    }//GEN-LAST:event_txtMenMouseClicked

    private void btnDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesActionPerformed
        // traduz a mensagem criptografadas
        String menCrip , mensResu;
        char aux1, aux2;
        menCrip= txtMenCri.getText();
        mensResu="";
        int chave = Integer.parseInt(deslocamento.getValue().toString());
        
        
        for(int i = 0; i < menCrip.length(); i++){
            //Tratamento espaco branco
            if (menCrip.charAt(i)== 32){
                mensResu+=" ";
            }
            
            //Tratamento Letras Minúsculas
            if(menCrip.charAt(i) >= 97 && menCrip.charAt(i) <=122){
                if ((menCrip.charAt(i)- chave) <97){
                     aux1 = (char) (menCrip.charAt(i) - chave);
                     aux2 = (char) (aux1 + 122);
                     mensResu= mensResu+ (char)(aux2 - 96);
                    
                    txtMenDes.setText(mensResu);
                }else{
                    mensResu= mensResu +(char)(menCrip.charAt(i)- chave);
                    txtMenDes.setText(mensResu);
                }
            }
            
            
            
            
        }
        
    }//GEN-LAST:event_btnDesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMensagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCri;
    private javax.swing.JButton btnDes;
    private javax.swing.JSpinner deslocamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMen;
    private javax.swing.JTextField txtMenCri;
    private javax.swing.JTextField txtMenDes;
    // End of variables declaration//GEN-END:variables
}
